import pygame

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

PLAYER_RADIUS = 20
LINE_WIDTH = 2
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_WRAP_SPAWN_TIMER = 2

SHOT_RADIUS = 5

POINTS_PER_KILL = 100
MAX_CONSEC_SHOT_MULTI = 5
BASE_CONSEC_SHOT_MULTI_INC = 0.1

pygame.font.init()
SCORE_FONT = pygame.font.Font(None, 36)
TITLE_FONT = pygame.font.Font(None, 144)
MENU_FONT = pygame.font.Font(None, 72)

SAVE_FILE = "player_data.json"